
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bitouristo_development
  password: <%= ENV['BITOURISTO_DATABASE_PASSWORD'] %>
  username: postgres

test:
  <<: *default
  database: bitouristo_test
  password: <%= ENV['BITOURISTO_DATABASE_PASSWORD'] %>
  username: postgres

production:
  <<: *default
  database: bitouristo_production
  username: bitouristo
  password: <%= ENV['BITOURISTO_DATABASE_PASSWORD'] %>
